### ISSUE TITLE
Add support for Let's Encrypt

### ISSUE THREAD

**Issue by esell** [esell/deb-simple#18]
Would be nice to support auto creation of Let's Encrypt certs

**Comment by paulkramme** [comment]
You could also use [caddyserver](https://caddyserver.com), which will give you automatic https, and then reverse proxy everything to this server.

**Comment by esell** [comment]
Migrating to self-hosted git repo. Issue has been re-created here: https://git.esheavyindustries.com/esell/deb-simple/issues/2

**Comment by esell** [comment]
gonna close this out as i don't think it helps much and would just complicate things. if you are using deb-simple and need let's encrypt, most of the major http servers support it :).
