### ISSUE TITLE
Access control?

### ISSUE THREAD

**Issue by paulkramme** [esell/deb-simple#20]
Is there a way to use this in a global production environment by blocking add/delete requests?

**Comment by esell** [comment]
Good idea, I've started work on an `apikeys` branch to play around with a few ideas...

**Comment by paulkramme** [comment]
Great!

**Comment by esell** [comment]
Just published [v1.3.0](https://github.com/esell/deb-simple/releases/tag/1.3.0) if you want to take it for a spin. The README has been updated with how to use the new functionality.

**Comment by esell** [comment]
Migrating to self-hosted git repo. Issue has been re-created here: https://git.esheavyindustries.com/esell/deb-simple/issues/3

**Comment by esell** [comment]
probably can close this since we support api keys now :)
