### ISSUE TITLE
deb-simple API client

### ISSUE THREAD

**Issue by xor-gate** [esell/deb-simple#22]
When integrating with other golang software. `deb-simple` could benefit from an API client package. E.g:

``` go
package main

import (
    "github.com/esell/deb-simple/client"
)

func main() {
    client.New(&client.Config {
     APIKey: "1337",
    })
    client.PublishDebFile("myfile.deb")
}
```

**Comment by paulkramme** [comment]
Wouldn't a simple system() call with the URL be enough?

**Comment by xor-gate** [comment]
System call, that is unacceptable! Golang has native support for HTTP transport. `os.Exec` as you mention as `system()` is 100% unportable across systems!

The native Client approach is fairly easy to implement.

**Comment by paulkramme** [comment]
Oh, sorry, i am a C guy, so this would be more difficult in C. Sorry if
this was disgusting to you :(

**Comment by xor-gate** [comment]
Ooh no, don't feel attacked. I know how you feel when writing in C/C++. I write mostly C for embedded systems and know how hard it is!

**Comment by paulkramme** [comment]
Oh, that is good, i am always concerned pissing someone off... The reason for a system call would be, that other languages could use it too, and cross platform wouldn't be a problem IMO. I will look into libcurl for C (and the equivalent for python). Let's see if we can do something 👍

**Comment by xor-gate** [comment]
Probably an API build on top of Curl + some sort of JSON library would take 400% more time than a package in Golang :+)

**Comment by esell** [comment]
Migrating to self-hosted git repo. Issue has been re-created here: https://git.esheavyindustries.com/esell/deb-simple/issues/4

**Comment by esell** [comment]
I think since deb-simple exposes REST endpoints, it might make sense to just have other go programs use those. I'll close this for now but if there is a good reason to add this we can open it back up.
