### ISSUE TITLE
MAINTAINER WANTED

### ISSUE THREAD

**Issue by esell** [esell/deb-simple#36]
As I am no longer using deb-simple in my day-to-day life, it has been mostly ignored as you can likely see from the issues/PRs. If you are interested in taking over and becoming the maintainer of deb-simple, please let me know

**Comment by esell** [comment]
Tagging a few folks who have contributed previously just in case any of them are interested :)

@dig412 @icholy

**Comment by dig412** [comment]
I'd be interested in doing this - what does it entail?

Cutting new releases / responding to issues / checking Travis builds?

**Comment by esell** [comment]
@dig412, pretty much :). Github gives me the ability to transfer owernship, so my thinking was I'd just transfer it over to someone and then they can take over from there: https://help.github.com/en/github/administering-a-repository/transferring-a-repository

**Comment by dig412** [comment]
Sure. Would you want to keep it under your account (it is your software after all) and assign me admin rights, or transfer it entirely to my username?

Equally it has taken me 10 days to reply to this issue, so I might not be the best steward...

**Comment by icholy** [comment]
I'm no longer using this project. So that's a no-go for me.

**Comment by esell** [comment]
How about this @dig412, I can add you as a contributor to this repo and we can see how things go, does that work? I don't want to push deb-simple on anyone so feel free to just ignore, I just figured I'd reach out to the folks who have contributed previously :).

@icholy, no worries! Just curious, what caused you to stop using it?

**Comment by icholy** [comment]
@esell using RPMs

**Comment by dig412** [comment]
@esell Sounds good, lets go for it.
